services:
  - type: web
    name: memeter-backend
    env: node
    buildCommand: npm ci --only=production
    startCommand: node server/production.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
    autoDeploy: true