services:
  - type: web
    name: memeter-backend
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
    autoDeploy: true