services:
  - type: web
    name: memeter-backend
    env: node
    buildCommand: npm install
    startCommand: npx tsx server/production.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/status
    autoDeploy: true