services:
  - type: web
    name: memeter-backend
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci && npm run build:server
    startCommand: node dist/index.js
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
