apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: memeter-api
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/cloudsql-instances: YOUR_PROJECT:us-central1:memeter-db
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '10'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/YOUR_PROJECT/memeter-api:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: '8080'
        - name: DB_HOST
          value: /cloudsql/YOUR_PROJECT:us-central1:memeter-db
        - name: DB_PORT
          value: '5432'
        - name: DB_USER
          value: postgres
        - name: DB_NAME
          value: memeter
        - name: PUMPPORTAL_WS_URL
          value: wss://pumpportal.fun/api/data
        - name: PUMPAPI_WS_URL
          value: wss://stream.pumpapi.io/
        - name: ALLOWED_ORIGINS
          value: https://your-app.vercel.app
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: latest
        - name: HELIUS_API_KEY
          valueFrom:
            secretKeyRef:
              name: helius-api-key
              key: latest
        resources:
          limits:
            memory: 1Gi
            cpu: '1'
